In [61]:
# Importing the Dependencies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [62]:
# Load the dataset to pandas Dataframe
# Dataset Link
# https://www.kaggle.com/datasets/arockiaselciaa/creditcardcsv
credit_card_data = pd.read_csv("creditcard.csv")

In [63]:
# First 5 rows of the Dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [64]:
# Last 5 rows of the Dataset
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [65]:
# Dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [66]:
# Checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [67]:
# Distribution of Legit Transaction and fraudulent transaction
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

# This dataset is Highly unbalanced
0 --> Normal Transaction
1 --> Fraudulent Transaction

In [68]:
# Seperating the Data for analysis
Legit = credit_card_data[credit_card_data['Class'] == 0] # pandas series datatype
Fraud = credit_card_data[credit_card_data['Class'] == 1] # pandas series datatype

In [69]:
print(Legit.shape)
print(Fraud.shape)

(284315, 31)
(492, 31)

In [70]:
# Statistical measures of Data
Legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

We can infer that 25% of the entire transaction Amount are less than 6$
Also, 50 % of the entire transaction Amount are less than 22$
and 75% of the entire transaction Amount are less than 75$

In [71]:
Fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

We can infer from Fraud Class that 25% of the entire transaction Amount are less than 1$
Also, 50 % of the entire transaction Amount are less than 9$
and 75% of the entire transaction Amount are less than 106$
Whereas max Fraud transaction accounted for 2125$
Count of Fraud transaction accounting to 492 heads
Mean value of Fraud transaction Amount accounting to $122 which is more than Legit Transaction Mean Amount

In [72]:
# Compare the values for both Transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Undersampling Technique to handle Imbalanced Dataset
Build a sample Dataset containing similar Distribution of normal Transactions and Fraudulent Transactions
Number of Fraudulent Transactions --> 492

In [73]:
# Select Random Sample from Legit Transactions to form Uniform or normal distibution with Fraud Transactions datapoints
Legit_sample = Legit.sample(n = 492,replace = False) # Randomly select data from 284315 data points and not First 492 records

In [74]:
# Concatenating Two DataFrames
credit_card_data_new =  pd.concat([Legit_sample,Fraud],axis = 0)

In [75]:
# First 5 records
credit_card_data_new.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
212190,138758.0,-0.256379,0.828703,0.063531,0.907773,0.939309,-0.996909,1.689988,-0.575652,-0.587027,...,0.096585,0.441652,-0.085017,-0.062078,-0.237070,-0.524772,-0.091542,-0.042813,60.00,0
124081,77168.0,1.212447,0.498605,0.740435,2.306762,0.010196,0.201900,-0.151724,-0.028028,-0.587173,...,0.103895,0.344114,-0.182068,-0.420548,0.588310,0.144568,0.019071,0.024988,10.59,0
173663,121588.0,1.974042,-1.224182,-0.378624,-0.542481,-0.935134,0.446617,-1.157956,0.044834,0.136138,...,-0.303389,-0.418311,0.246088,0.059782,-0.574370,0.483391,0.000705,-0.014459,99.95,0
101974,68000.0,-0.904582,0.199300,0.755082,-1.537265,-0.630261,-0.690272,-0.507224,0.696208,-1.342672,...,0.238887,0.342738,0.072770,0.091381,-0.140561,-0.442120,0.152985,-0.019701,37.40,0
24287,33158.0,1.046523,-1.243952,1.031016,-0.227080,-1.699583,-0.262421,-0.867896,-0.027001,0.012683,...,0.102611,0.158803,-0.135768,0.454293,0.350483,-0.263248,0.029592,0.053425,162.64,0

In [76]:
# Last 5 Records
credit_card_data_new.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [77]:
# Checking the Distribution of the Data
credit_card_data_new['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [78]:
# Comapare the values of Both Classes
credit_card_data_new.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,90628.837398,0.077008,0.030059,0.036024,0.052753,0.110394,0.018648,0.001217,-0.039283,-0.019927,...,0.011571,0.079146,0.047872,0.029437,0.027749,-0.019068,-0.038357,0.016876,0.009932,77.726362
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

The nature of the Dataset is not changed and Difference still exists. It helps Machine Learning Model to detect whether the transaction is Legit or Fraudulent

In [79]:
# Splitting the Data into Independent(Input Feature) and Dependent(Output Feature) variable
X = credit_card_data_new.drop(columns='Class',axis = 1)
y = credit_card_data_new['Class']

In [80]:
X.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
212190,138758.0,-0.256379,0.828703,0.063531,0.907773,0.939309,-0.996909,1.689988,-0.575652,-0.587027,...,-0.115444,0.096585,0.441652,-0.085017,-0.062078,-0.237070,-0.524772,-0.091542,-0.042813,60.00
124081,77168.0,1.212447,0.498605,0.740435,2.306762,0.010196,0.201900,-0.151724,-0.028028,-0.587173,...,-0.018720,0.103895,0.344114,-0.182068,-0.420548,0.588310,0.144568,0.019071,0.024988,10.59
173663,121588.0,1.974042,-1.224182,-0.378624,-0.542481,-0.935134,0.446617,-1.157956,0.044834,0.136138,...,-0.249791,-0.303389,-0.418311,0.246088,0.059782,-0.574370,0.483391,0.000705,-0.014459,99.95
101974,68000.0,-0.904582,0.199300,0.755082,-1.537265,-0.630261,-0.690272,-0.507224,0.696208,-1.342672,...,0.145778,0.238887,0.342738,0.072770,0.091381,-0.140561,-0.442120,0.152985,-0.019701,37.40
24287,33158.0,1.046523,-1.243952,1.031016,-0.227080,-1.699583,-0.262421,-0.867896,-0.027001,0.012683,...,0.403456,0.102611,0.158803,-0.135768,0.454293,0.350483,-0.263248,0.029592,0.053425,162.64

In [81]:
y.head()

212190    0
124081    0
173663    0
101974    0
24287     0
Name: Class, dtype: int64

In [109]:
# Split the Data into Training Data and Testing Data
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,stratify=y,random_state=2) # Creating 4 arrays
# stratify ensures evenly distribution of 2 classes in X_train and X_test

In [111]:
# Displaying the shape of the Distribution
print(X_train.shape),print(X_test.shape),print(y_train.shape),print(y_test.shape)

(787, 30)
(197, 30)
(787,)
(197,)

(None, None, None, None)

#### Model Training

In [135]:
model = LogisticRegression(max_iter= 2000)

In [137]:
# Training the Logistic Regression model with Training data
model.fit(X_train,y_train)

D:\AnacondaApp\Data\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=2000)

### Model Evaluation

In [140]:
# Accuracy score on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,y_train)

In [142]:
# Evaluating Accuracy on training data
print("Accuracy on Training Data : ",training_data_accuracy)

Accuracy on Training Data :  0.9580686149936467

Out of 100 predictions our build model can predict 95% data correctly

In [146]:
# Accuracy score on Test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,y_test)

In [148]:
# Evaluating Accuracy on test data
print("Accuracy on Training Data : ",test_data_accuracy)

Accuracy on Training Data :  0.9289340101522843

 From the Accuracy score of Both Data we can conclude we got generalised model with slight diversion in accuracy score
We have not faced Overfiiting and Underfitting model problem
1) Overfitting - Accuracy of Training data is good but the Accuracy of the test data doesn't sync with the Accuracy of the 
Training data which is low
2) Underfitting - Accuracy of the Training data is low whereas Accuracy of the Test data is high